# These are supported funding model platforms

github: mrz1836
custom: https://mrz1818.com/?tab=tips&utm_source=github&utm_medium=sponsor-link&utm_campaign=atlas&utm_term=atlas&utm_content=atlas
buy_me_a_coffee: mrz1818
